---
title: "Learner Persona: Mia"
output: github_document
---


## General Background
- About to start her sophomore year in college
- Transferring to Duke from a large public university
- She's looking forward to being at a smaller school, and is also excited about Duke basketball! 
- Generally enjoys her math and statistics classes, but she wants to study sociology

### Starting Point
- Took an introductory statistics course at her previous university where they used a point-and-click software 
- Has experience using Excel but has never written code.

### Needs 
- She's taking a regression course in the fall that assumes students already have some familiarity with R. 
- She's taking the workshop to start learning R, mainly data wrangling and data visualization. 
- She is also looking for resources so she can keep practicing on her own after the workshop. 

### Special Considerations 
- She feels a little intimidated, because she's about to enter a new environment and already feels like she's playing catch up
