---
title: "Assessments"
output: 
  learnr::tutorial:
    progressive: true
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE)
```

```{r load-packages}
library(tidyverse)
library(mosaicData)
library(lubridate)
```

## Exercise 1

Consider the code below: 

```{r echo = TRUE, eval = F}
ggplot(data = diamonds, aes(x = carat, y = price)) +
  geom_point(aes(shape = cut), color = "blue")
```

```{r aes-quest}
question("Which of the following best describes the points on the plot?",
    answer("The shape is the same for all points."),
    answer("The color is the same for all points.", correct = TRUE),
    answer("The color and shape are the same for all points.")
  )
```

<!-- 
- Fix headings, so it's a continuous problem 
- Fix day of the week (is Monday correct?), put days in order
- Add itermediate problem, where they have to fill in code inside the brackets
- Fix questions 
- Add codebook at top
- Add problem intro briefly explaining the data and variables used
-->

## Parson's Problem 

### Parson's Problem - 1

```{r echo = F}
Riders <- Riders %>%
  mutate(month = month(date)) %>%
  mutate(month = case_when(
    month == 4 ~ "April", 
    month == 5 ~ "May", 
    month == 6 ~ "June", 
    month == 7 ~ "July", 
    month == 8 ~ "August", 
    TRUE ~ "November"
  ))
```


```{r echo = FALSE, eval = TRUE}
ggplot(data = Riders, aes(x = highT, y = riders, color = clouds)) + 
  geom_point() + 
  labs(x = "High Temperature", 
       y = "Riders", 
       color = "Cloud Cover",
       title = "Riders vs. High Temp. & Cloud Cover", 
       subtitle = "by Weekday") +
  facet_wrap(~ weekday)
```

Fill in the blanks in the partial code to recreate the plot shown above. 

```{r parsons-1, exercise = TRUE, exercise.eval = FALSE}
# replace blanks with the correct values to recreate the plot above.
ggplot(data = Riders, aes(x = highT, y = _____, color = _____)) + 
  geom_point() + 
  labs(x = "_____", 
       y = "Riders", 
       color = "Cloud Cover",
       title = "Riders vs. High Temp. & Cloud Cover", 
       subtitle = "_____") +
  facet_wrap(~ _____)
```

### Parson's Problem - 2

Fill in the code to recreate the plot. 
```{r echo = FALSE, eval = TRUE}
ggplot(data = Riders, aes(x = clouds, y = precip, color = weekday)) + 
  geom_point() + 
  labs(x = "Cloud Cover", 
       y = "Precipitation", 
       color = "Weekday",
       title = "Precipitation vs. Cloud Cover & Weekday", 
       subtitle = "by Month") +
  facet_wrap(~ month)
```

```{r parsons-2, exercise = TRUE, exercise.eval = FALSE}
# Fill in the code to recreate the plot shown above 
ggplot(data = Riders, aes(_____)) + 
  geom_point() + 
  labs(_____)+
  facet_wrap(_____)
```

### Parson's Problem - 3

Recreate the plot. 

```{r echo = FALSE, eval = TRUE}
ggplot(data = Riders, aes(x = lowT, y = riders, color = day)) + 
  geom_point() + 
  labs(x = "Low Temperature", 
       y = "Riders", 
       color = "Day",
       title = "Riders. vs. Low Temp & Day", 
       subtitle = "Weekdays vs. Weekends") +
  facet_wrap(~ weekday)
```

```{r parsons-3, exercise = TRUE, exercise.eval = FALSE}
# Write code to recreate the plot shown above 

```

